"use client";

import React from 'react';
import Link from 'next/link';
import { Plus, FileText, TrendingUp, Calendar, ArrowRight } from 'lucide-react';
import { BlogPostRecord } from '../types';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';

export default function Dashboard() {
  const recentPosts: BlogPostRecord[] = [
    { id: '1', topic: 'Top 10 Marketing Strategies for 2025', date: '2024-05-10', status: 'Published' },
    { id: '2', topic: 'Understanding Neural Networks', date: '2024-05-12', status: 'Draft' },
    { id: '3', topic: 'Minimalist Interior Design Guide', date: '2024-05-14', status: 'Scheduled' },
  ];

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex flex-col md:flex-row justify-between md:items-end gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">Dashboard</h1>
          <p className="text-slate-500 mt-2">Overview of your automated blog content and performance.</p>
        </div>
        <Link href="/generate">
          <Button className="bg-indigo-600 hover:bg-indigo-700 shadow-md gap-2">
            <Plus size={18} /> Create New
          </Button>
        </Link>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <StatCard title="Total Posts" value="12" icon={FileText} className="text-blue-600 bg-blue-50 border-blue-100" />
        <StatCard title="Published" value="8" icon={TrendingUp} className="text-green-600 bg-green-50 border-green-100" />
        <StatCard title="Scheduled" value="4" icon={Calendar} className="text-purple-600 bg-purple-50 border-purple-100" />
      </div>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div className="space-y-1">
            <CardTitle>Recent Activity</CardTitle>
            <CardDescription>Latest blog posts generated by the AI.</CardDescription>
          </div>
          <Button variant="ghost" size="sm" className="text-indigo-600">View All</Button>
        </CardHeader>
        <CardContent>
          <div className="space-y-1">
            {recentPosts.map((post) => (
              <div key={post.id} className="flex items-center justify-between p-3 hover:bg-slate-50 rounded-lg transition-colors group">
                <div className="space-y-1">
                  <h4 className="font-medium text-slate-900 group-hover:text-indigo-600 transition-colors">{post.topic}</h4>
                  <p className="text-xs text-slate-500">Updated on {post.date}</p>
                </div>
                <div className="flex items-center gap-4">
                  <StatusBadge status={post.status} />
                  <Button variant="ghost" size="icon" className="opacity-0 group-hover:opacity-100 transition-opacity h-8 w-8">
                    <ArrowRight size={16} />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
      
      <div className="bg-gradient-to-r from-indigo-600 to-violet-600 rounded-xl shadow-lg text-white p-8 flex flex-col md:flex-row items-center justify-between gap-6">
        <div>
          <h3 className="text-2xl font-bold mb-2">Automate your weekly content</h3>
          <p className="text-indigo-100 max-w-xl">Set up a schedule and let AI research and draft posts automatically based on your favorite topics.</p>
        </div>
        <Button variant="secondary" className="font-bold text-indigo-600">
          Configure Schedule
        </Button>
      </div>
    </div>
  );
}

const StatCard = ({ title, value, icon: Icon, className }: { title: string, value: string, icon: any, className?: string }) => (
  <Card>
    <CardContent className="p-6 flex items-center gap-4">
      <div className={`p-3 rounded-lg ${className}`}>
        <Icon size={24} />
      </div>
      <div>
        <p className="text-slate-500 text-sm font-medium">{title}</p>
        <p className="text-2xl font-bold text-slate-900">{value}</p>
      </div>
    </CardContent>
  </Card>
);

const StatusBadge = ({ status }: { status: string }) => {
  let variant: "default" | "secondary" | "outline" | "success" | "warning" = "secondary";
  if (status === 'Published') variant = "success";
  if (status === 'Draft') variant = "secondary";
  if (status === 'Scheduled') variant = "warning";
  
  return <Badge variant={variant}>{status}</Badge>;
};